#!/bin/bash

git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(js)$ ]]; then
  if [[ -f $FILE ]]; then
    # Check for word debugger
    RESULT=$(grep "debugger" "$FILE")
    if [ ! -z $RESULT ]; then
      echo -e "\e[1;31m\tERROR: File "$FILE" contains debuggers.\e[0m" >&2
      exit 1
    fi

    # Check syntax errors
    jscs "$FILE"
    if [ $? -ne 0 ]; then
      echo -e "\e[1;31m\tAborting commit due to files with syntax errors.\e[0m" >&2
      exit 1
    fi
  fi
fi
done || exit $?
